# Generated by Django 4.1 on 2024-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_colstypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=255)),
                ('score', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
            ],
        ),
    ]
