# Generated by Django 4.1 on 2024-06-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_filecontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
