# Generated by Django 4.1 on 2024-06-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColsTypes',
        ),
        migrations.DeleteModel(
            name='FileContent',
        ),
    ]
